In [1]:
import numpy as np

In [2]:
arrA = [[2,-1],[-7,4]]

In [3]:
arrA

[[2, -1], [-7, 4]]

In [4]:
arrB = [[-3,0],[17,2]]

In [5]:
arrB

[[-3, 0], [17, 2]]

In [6]:
arrC = arrA + arrB

In [7]:
arrC

[[2, -1], [-7, 4], [-3, 0], [17, 2]]

In [8]:
matA = np.array(arrA)

In [9]:
matA

array([[ 2, -1],
       [-7,  4]])

In [10]:
matB = np.array(arrB)

In [11]:
matB

array([[-3,  0],
       [17,  2]])

In [12]:
matC = matA + matB

In [13]:
matC

array([[-1, -1],
       [10,  6]])

In [14]:
arrA = [[3,4,0],[-2,6,-3],[7,-4,1]]

In [15]:
arrA

[[3, 4, 0], [-2, 6, -3], [7, -4, 1]]

In [16]:
mul_arrA = 2*arrA

In [17]:
mul_arrA

[[3, 4, 0], [-2, 6, -3], [7, -4, 1], [3, 4, 0], [-2, 6, -3], [7, -4, 1]]

In [18]:
matA = np.array(arrA)

In [19]:
matA

array([[ 3,  4,  0],
       [-2,  6, -3],
       [ 7, -4,  1]])

In [20]:
mul_matA = 2 * matA

In [21]:
mul_matA

array([[ 6,  8,  0],
       [-4, 12, -6],
       [14, -8,  2]])

In [37]:
vecA = np.array([2,5,-1])

In [38]:
vecA

array([ 2,  5, -1])

In [39]:
matAvecA = np.dot(matA, vecA)

In [40]:
matAvecA

array([26, 29, -7])