In [3]:
import numpy as np
import tensorflow as tf

np.random.seed(0)
tf.random.set_seed(0)

num_input=2
num_neurons=3
Wf=tf.Variable(tf.random.normal(shape=[num_input, num_neurons]))
Wr=tf.Variable(tf.random.normal(shape=[num_neurons, num_neurons]))
bias=tf.Variable(tf.zeros([1,num_neurons]))

#pseudo_data
xt0_batch=np.array([[0,1],[2,3],[4,5]]).astype(np.float32)
xt1_batch=np.array([[100,101],[102,103],[104,105]]).astype(np.float32)

def forward_pass(xt0,xt1):
    yt0=tf.tanh(tf.matmul(xt0,Wf)+bias)
    yt1=tf.tanh(tf.matmul(yt0,Wr)+tf.matmul(xt1,Wf)+bias)
    return yt0,yt1

yt0_output,yt1_output=forward_pass(xt0_batch,xt1_batch)
tf.print(yt0_output)
tf.print(yt1_output)


[[-0.776318431 -0.844548464 0.438419849]
 [-0.0857750699 -0.993522227 0.516408086]
 [0.698345721 -0.999749422 0.586677969]]
[[1 -1 0.999998629]
 [1 -1 0.999998331]
 [1 -1 0.999997377]]
